### ISSUE TITLE
[bug] messages written out of order

### ISSUE THREAD

**Issue by simonhdickson** [uw-labs/freezer#20]
We have tried writing messages from nats to s3 via freezer, when reading back the messages and comparing to the original queue we sometimes notice messages being read out of order (this doesn't always seem to happen).

We have seen it write well over 80,000 messages sometimes before going out of order and also seen it occur within writing under 1,000.

It is unknown if the issues is specifying related to nats or is a general freezer issue.

Our component that experiences this problem is currently disabled but I'll update this ticket with more information when it fails.

**Comment by mjgarton** [comment]
I suspect this turned out to be a nats-streaming issue if nats-streaming was involved.

If not, did any more information come to light, or can this be closed now?  @simonhdickson

**Comment by simonhdickson** [comment]
Yes this can be closed, likely was nats related.
